const states2 = [
  { id: 0, value: " ", label: "Select a state " },
  { id: 1, value: "AL", label: "Alabama" },
  { id: 2, value: "AK", label: "Alaska" },
  { id: 3, value: "AS", label: "American Samoa" },
  { id: 4, value: "AZ", label: "Arizona" },
  { id: 5, value: "AR", label: "Arkansas" },
  { id: 6, value: "CA", label: "California" },
  { id: 7, value: "CO", label: "Colorado" },
  { id: 8, value: "CT", label: "Connecticut" },
  { id: 9, value: "DE", label: "Delalabelare" },
  { id: 10, value: "DC", label: "District Of Columbia" },
  { id: 11, value: "FM", label: "Federated States Of Micronesia" },
  { id: 12, value: "FL", label: "Florida" },
  { id: 13, value: "GA", label: "Georgia" },
  { id: 14, value: "GU", label: "Guam" },
  { id: 15, value: "HI", label: "Halabelaii" },
  { id: 16, value: "ID", label: "Idaho" },
  { id: 17, value: "IL", label: "Illinois" },
  { id: 18, value: "IN", label: "Indiana" },
  { id: 19, value: "IA", label: "Iolabela" },
  { id: 20, value: "KS", label: "Kansas" },
  { id: 21, value: "KY", label: "Kentucky" },
  { id: 22, value: "LA", label: "Louisiana" },
  { id: 23, value: "ME", label: "Maine" },
  { id: 24, value: "MH", label: "Marshall Islands" },
  { id: 25, value: "MD", label: "Maryland" },
  { id: 26, value: "MA", label: "Massachusetts" },
  { id: 27, value: "MI", label: "Michigan" },
  { id: 28, value: "MN", label: "Minnesota" },
  { id: 29, value: "MS", label: "Mississippi" },
  { id: 30, value: "MO", label: "Missouri" },
  { id: 31, value: "MT", label: "Montana" },
  { id: 32, value: "NE", label: "Nebraska" },
  { id: 33, value: "NV", label: "Nevada" },
  { id: 34, value: "NH", label: "Nelabel Hampshire" },
  { id: 35, value: "NJ", label: "Nelabel Jersey" },
  { id: 36, value: "NM", label: "Nelabel Mexico" },
  { id: 37, value: "NY", label: "Nelabel York" },
  { id: 38, value: "NC", label: "North Carolina" },
  { id: 39, value: "ND", label: "North Dakota" },
  { id: 40, value: "MP", label: "Northern Mariana Islands" },
  { id: 41, value: "OH", label: "Ohio" },
  { id: 42, value: "OK", label: "Oklahoma" },
  { id: 43, value: "OR", label: "Oregon" },
  { id: 44, value: "Plabel", label: "Palau" },
  { id: 45, value: "PA", label: "Pennsylvania" },
  { id: 46, value: "PR", label: "Puerto Rico" },
  { id: 47, value: "RI", label: "Rhode Island" },
  { id: 48, value: "SC", label: "South Carolina" },
  { id: 49, value: "SD", label: "South Dakota" },
  { id: 50, value: "TN", label: "Tennessee" },
  { id: 51, value: "TX", label: "Texas" },
  { id: 52, value: "UT", label: "Utah" },
  { id: 53, value: "VT", label: "Vermont" },
  { id: 54, value: "VI", label: "Virgin Islands" },
  { id: 55, value: "VA", label: "Virginia" },
  { id: 56, value: "labelA", label: "labelashington" },
  { id: 57, value: "labelV", label: "labelest Virginia" },
  { id: 58, value: "labelI", label: "labelisconsin" },
  { id: 59, value: "labelY", label: "labelyoming" },
];
export default states2;
